// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emrbosuzmtgyashgxeum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtcmJvc3V6bXRneWFzaGd4ZXVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NjE0NjAsImV4cCI6MjA2NjIzNzQ2MH0.SEcI7OzzIhufq22qNPXbVvZWE9sh6DbS498VyouSyeA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});